### PR TITLE
Fix "./battery: line 78: [: ==: unary operator expected" on tcsh and …

### PR DESCRIPTION
**Pull request by tupinek**
…bash.

### CODE REVIEW

**Comment by minimenchmuncher** [comment]
What OS/Distro are you using? Bash version?

**Comment by tupinek** [comment]
pepa:~> cat /etc/debian_version 
8.1
pepa:~> tcsh --version
tcsh 6.18.01 (Astron) 2012-02-14 (x86_64-unknown-linux) options wide,nls,dl,al,kan,rh,nd,color,filec
pepa:~> bash --version
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by minimenchmuncher** [comment]
Interesting. I'm using testing/jessie, but the same versions of everything else, and am not seeing that problem. However, I tested it with your addition, and it doesn't seem to change the operation at all. I'm not going to merge, but I will include the change in my next commit.

About using using the `tcsh` shell, if you just do `tcsh battery`, I get an error that says `Badly placed ()'s`. Battery is written as a bash script (see the shebang), meant to be run `./battery`, and I have no idea how it might perform in other shells with other syntaxes - except perhaps zsh, but I haven't tested it yet.

**Comment by minimenchmuncher** [comment]
Can you test that this most recent version works on your computer? It's working over here.

**Comment by tupinek** [comment]
about tcsh: Oooh.. You are right, i was completly bad.. That's bash only.

**Comment by tupinek** [comment]
When i am charging upower with grep returns nothing:
pepa:~> upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'state'
    state:               fully-charged
pepa:~> upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'state' | grep -o 'discharging\|charging'
Then read don't have number and bash warn.

New version is functional. Thanks.

**Comment by minimenchmuncher** [comment]
Hm - there wasn't an option before for `fully-charged`. There is now. Should be working

**Comment by tupinek** [comment]
ok, thanks.

**Pull request closed without merging**
